### ISSUE TITLE
Don't show the "Loading MIDlet" dialog when only the BG MIDlet is running

### ISSUE THREAD

**Issue by marco-c** [andreasgal/j2me.js#931]

**Comment by mykmelez** [comment]
Additionally, it'd be useful to show something else that explains to the user what the app is doing, since the user will see a screenshot of the app in their "recent apps" view when the BG midlet is running, and they'll see the app itself before the FG midlet has a chance to start, when they first switch to the app while the BG midlet is running.

**Comment by marco-c** [comment]
Exactly, I wanted to file an issue for this as well, but I guess we could make this issue cover both things.
I see two options:
- periodically take screenshots of the canvas, show the screenshot of the canvas when the BG MIDlet is running;
- show a placeholder image (for example, a white image with the symbol of the MIDlet in the center).

Option 2 would probably be better.
