### ISSUE TITLE
remove old instrumentation and profiling code

### ISSUE THREAD

**Issue by mykmelez** [andreasgal/j2me.js#989]
The old instrumentation and profiling code in instrument.js (and elsewhere) is no longer hooked up to the new VM, so we should remove it from the codebase.

**Comment by yxl** [comment]
@mykmelez BTW, what is the replacement of the old instrumentation to let me view the Java methods' calling costs and counts?

**Comment by mykmelez** [comment]
cc: @mbebenita and @brendandahl for an explanation of how to profile method call costs/counts in the new VM.

**Comment by mbebenita** [comment]
The VM has several profiling tools. The simplest feature is to use counters. For instance, `runtime.ts` defines several: `runtimeCounter`, `nativeCounter`, etc ... these should only ever be used in non release builds.

To use them, just sprinkle calls to `runtimeCounter.count("string")`. To see the accumulated counts, press the `Dump Counters` button, or `Clear Counters` if you want to reset them.

The second, more heavy weight profiling tool is to build with `PROFILE=1 make`. This will include Shumway's timeline viewer. One way to use it is to manually insert calls to `timeline.enter` / `timeline.leave` around code blocks that you're interested in measuring. 

If you want to record every method call, change the line in `runtime.ts` from:

```
if (false && methodTimeline) { 
```
to
```
if (false && methodTimeline) { 
```

This will wrap all methods with calls to `methodTimeline.enter` /  `methodTimeline.leave`. The resulting timeline is a very detailed flame chart of the execution. Because of the fine grained nature of this instrumentation, timing for very short lived events may not be recorded accurately.

You can get creative with the timelines. The API looks something like this:

```
timeline.enter(name: string, details?: Object);
timeline.leave(name?: string, details?: Object);
```

You must pair the `enter` and `leave` events but you don't necessarily need to specify arguments for `name` and `details`.

The `name` argument can be any string and it specifies a event type. The timeline view will draw different types of events in different colors. It will also give you some statistics about the number of times a certain event type was seen, how long it took, etc.. 

The `details` is an object, whose properties are shown when you hover over a timeline segment in the profiler view. You can specify this object when you call `timeline.enter` or when you call `timeline.leave`. Usually, you have more information when you call `leave` so that's a more convenient place to put it.

The way in which you come up with event names can produce different results. In the `profilingWrapper` function, the `key` is used to specify the even type. At the moment, this is set to `MethodType[methodType]`, but you can easily set it to `implKey` which will give you a very detailed output.

**Comment by yxl** [comment]
@mbebenita Thanks. Really helpful explanation and powerful profiling tools.
